# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Vignesh Hirudayakanth
tagline:          'Computer Engineering, Food, Web Development, Starcraft'
url:              http://www.vigneshka.com
shorturl:         vigneshka.com

baseurl:          /
author:           Vignesh Hirudayakanth
  name:           'Vignesh Hirudayakanth'
  url:            https://twitter.com/vigneshka

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/vigneshka/vigneshka.github.io

pages_list:
  Contact:        '/contact/'
  Blog:           '/blog/'
  Feed:           '/atom.xml'

# Allow URL Redirects:
# * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from